### ISSUE TITLE
Task list 1

### ISSUE THREAD

**Issue by AitanaFischer** [AitanaFischer/markdown-portfolio#2]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by AitanaFischer** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by AitanaFischer** [comment]
- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [ ] This item is not complete.
